name: shared
description: "버스 추적 앱 공통 코드 라이브러리"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0  # 지도 관련 공통 코드
  provider: ^6.1.2             # 상태 관리
  socket_io_client: ^3.0.2     # 소켓 통신
  http: ^1.3.0                 # HTTP 통신

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
